In [ ]:
import pandas as pd
import numpy as np

In [ ]:
patientheartrate = pd.read_csv(r'patient_heart_rate.csv')
patientheartrate

       1    Mickéy Mousé    56       70kgs   72   69   71    -  -.1  -.2
0    2.0     Donald Duck  34.0   154.89lbs    -    -    -   85   84   76
1    3.0      Mini Mouse  16.0         NaN    -    -    -   65   69   72
2    4.0  Scrooge McDuck   NaN       78kgs   78   79   72    -    -    -
3    5.0    Pink Panther  54.0  198.658lbs    -    -    -   69  NaN   75
4    6.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
5    7.0    Dewey McDuck  19.0       56kgs    -    -    -   71   78   75
6    8.0      Scööpy Doo  32.0       78kgs   78   76   75    -    -    -
7    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
8    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
9    NaN             NaN   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
10   9.0     Huey McDuck  52.0      189lbs    -    -    -   68   75   72
11  10.0    Louie McDuck  12.0       45kgs    -    -    -   92   95   87
12  11.0       Henry Nam   NaN       60kgs   78   75   72    -    -    -
13  12.0     Michel Long  34.0         NaN   65   67   55    -    -    -
14  13.0      Tana Ricky   NaN         NaN    -    -    -   68   72   70
15  14.0        UniLever   NaN         NaN  NaN  NaN  NaN  NaN  NaN  NaN
16  15.0             NaN  52.0      180lbs    -    -    -   68   75   72

In [ ]:
column_names = ["ID", "Name", "Age" ,"Weight", "m0006", "m0612", "m1218", "f0006", "f0612", "f1218"]
patientheartrate = pd.read_csv(r'/content/patient_heart_rate.csv', names=column_names)
print(patientheartrate.head())

    ID            Name   Age      Weight m0006 m0612 m1218 f0006 f0612 f1218
0  1.0    Mickéy Mousé  56.0       70kgs    72    69    71     -     -     -
1  2.0     Donald Duck  34.0   154.89lbs     -     -     -    85    84    76
2  3.0      Mini Mouse  16.0         NaN     -     -     -    65    69    72
3  4.0  Scrooge McDuck   NaN       78kgs    78    79    72     -     -     -
4  5.0    Pink Panther  54.0  198.658lbs     -     -     -    69   NaN    75

In [ ]:
patientheartrate[['Firstname','Lastname']] = patientheartrate['Name'].str.split(expand = True)
patientheartrate = patientheartrate.drop('Name',axis = 1)
print(patientheartrate)

      ID   Age      Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname  \
0    1.0  56.0       70kgs    72    69    71     -     -     -    Mickéy
1    2.0  34.0   154.89lbs     -     -     -    85    84    76    Donald
2    3.0  16.0         NaN     -     -     -    65    69    72      Mini
3    4.0   NaN       78kgs    78    79    72     -     -     -   Scrooge
4    5.0  54.0  198.658lbs     -     -     -    69   NaN    75      Pink
5    6.0  52.0      189lbs     -     -     -    68    75    72      Huey
6    7.0  19.0       56kgs     -     -     -    71    78    75     Dewey
7    8.0  32.0       78kgs    78    76    75     -     -     -    Scööpy
8    NaN   NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN
9    NaN   NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN
10   NaN   NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN
11   9.0  52.0      189lbs     -     -     -    68    75    72      Huey
12  10.0  12.0       45kgs     -     -     -    92    95    87     Louie
13  11.0   NaN       60kgs    78    75    72     -     -     -     Henry
14  12.0  34.0         NaN    65    67    55     -     -     -    Michel
15  13.0   NaN         NaN     -     -     -    68    72    70      Tana
16  14.0   NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever
17  15.0  52.0      180lbs     -     -     -    68    75    72       NaN

   Lastname
0     Mousé
1      Duck
2     Mouse
3    McDuck
4   Panther
5    McDuck
6    McDuck
7       Doo
8       NaN
9       NaN
10      NaN
11   McDuck
12   McDuck
13      Nam
14     Long
15    Ricky
16     None
17      NaN

In [ ]:
weight = patientheartrate['Weight']
for i in range(0,len(weight)):
  x = str(weight[i])
  if 'lbs' in x[-3:]:
    x = x[:-3:]
    float_x = float(x)
    y = int(float_x/2.2)
    y = str(y) + 'kgs'
    weight[i] = y
print(patientheartrate)

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
8    NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
9    NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
10   NaN   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN      NaN
11   9.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

<ipython-input-40-fc71c46746ca>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
<ipython-input-40-fc71c46746ca>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
<ipython-input-40-fc71c46746ca>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
<ipython-input-40-fc71c46746ca>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y
<ipython-input-40-fc71c46746ca>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weight[i] = y

In [ ]:
patientheartrate.dropna(how="all", inplace = True)
print(patientheartrate)

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
11   9.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

In [ ]:
patientheartrate = patientheartrate.drop_duplicates(subset=["Firstname", "Lastname", "Age", "Weight"])
print(patientheartrate)

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -    Mickéy    Mousé
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -    Scööpy      Doo
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

In [ ]:
patientheartrate.Firstname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
patientheartrate.Lastname.replace({r'[^\x00-\x7F]+':''}, regex=True, inplace=True)
print(patientheartrate)

      ID   Age Weight m0006 m0612 m1218 f0006 f0612 f1218 Firstname Lastname
0    1.0  56.0  70kgs    72    69    71     -     -     -     Micky     Mous
1    2.0  34.0  70kgs     -     -     -    85    84    76    Donald     Duck
2    3.0  16.0    NaN     -     -     -    65    69    72      Mini    Mouse
3    4.0   NaN  78kgs    78    79    72     -     -     -   Scrooge   McDuck
4    5.0  54.0  90kgs     -     -     -    69   NaN    75      Pink  Panther
5    6.0  52.0  85kgs     -     -     -    68    75    72      Huey   McDuck
6    7.0  19.0  56kgs     -     -     -    71    78    75     Dewey   McDuck
7    8.0  32.0  78kgs    78    76    75     -     -     -      Scpy      Doo
12  10.0  12.0  45kgs     -     -     -    92    95    87     Louie   McDuck
13  11.0   NaN  60kgs    78    75    72     -     -     -     Henry      Nam
14  12.0  34.0    NaN    65    67    55     -     -     -    Michel     Long
15  13.0   NaN    NaN     -     -     -    68    72    70      Tana    Ricky
16  14.0   NaN    NaN   NaN   NaN   NaN   NaN   NaN   NaN  UniLever     None
17  15.0  52.0  81kgs     -     -     -    68    75    72       NaN      NaN

In [ ]:
# vd7 lấy index của các dòng thiếu thông tin age và weight

index_ageweightnull = patientheartrate[patientheartrate['Age'].isna() & patientheartrate['Weight'].isna()].index
index_ageweightnull

Index([], dtype='int64')

In [ ]:
patientheartrate.drop(index_ageweightnull, inplace=True)

In [ ]:
patientheartrate["Age"].fillna(patientheartrate["Age"].mean(), inplace=False)

0     56.0
1     34.0
2     16.0
3     36.1
4     54.0
5     52.0
6     19.0
7     32.0
12    12.0
13    36.1
14    34.0
17    52.0
Name: Age, dtype: float64

In [ ]:
# Vấn đề 8
#Melt the sex + time range columns in single column
patientheartrate = pd.melt(patientheartrate, id_vars=["ID","Age","Weight","Firstname","Lastname"],value_name="PulseRate", var_name="sex_and_time").sort_values(["ID","Age","Weight","Firstname","Lastname"])

# Extract sex, hour lower bound and hour upper bound group
tmp_patientheartrate = patientheartrate["sex_and_time"].str.extract("(\D)(\d+)(\d{2})", expand=True)
# Name columns
tmp_patientheartrate.columns = ["sex", "hours_lower", "hours_upper"]

# Create time columns based on "hours_lower" and "hours_upper" columns
tmp_patientheartrate["Time"] = tmp_patientheartrate["hours_lower"] + "." + tmp_patientheartrate["hours_upper"]

# Merge

patientheartrate = pd.concat([patientheartrate, tmp_patientheartrate], axis = 1)

# Drop unnecessary columns and rows
patientheartrate = patientheartrate.drop(["sex_and_time", "hours_lower", "hours_upper"], axis = 1)
patientheartrate = patientheartrate.dropna()
patientheartrate.to_csv("outputcleanup.csv", index=False)
print(patientheartrate)

      ID   Age Weight Firstname Lastname PulseRate sex   Time
0    1.0  56.0  70kgs     Micky     Mous        72   m  00.06
12   1.0  56.0  70kgs     Micky     Mous        69   m  06.12
24   1.0  56.0  70kgs     Micky     Mous        71   m  12.18
36   1.0  56.0  70kgs     Micky     Mous         -   f  00.06
48   1.0  56.0  70kgs     Micky     Mous         -   f  06.12
60   1.0  56.0  70kgs     Micky     Mous         -   f  12.18
1    2.0  34.0  70kgs    Donald     Duck         -   m  00.06
13   2.0  34.0  70kgs    Donald     Duck         -   m  06.12
25   2.0  34.0  70kgs    Donald     Duck         -   m  12.18
37   2.0  34.0  70kgs    Donald     Duck        85   f  00.06
49   2.0  34.0  70kgs    Donald     Duck        84   f  06.12
61   2.0  34.0  70kgs    Donald     Duck        76   f  12.18
4    5.0  54.0  90kgs      Pink  Panther         -   m  00.06
16   5.0  54.0  90kgs      Pink  Panther         -   m  06.12
28   5.0  54.0  90kgs      Pink  Panther         -   m  12.18
40   5.0  54.0  90kgs      Pink  Panther        69   f  00.06
64   5.0  54.0  90kgs      Pink  Panther        75   f  12.18
5    6.0  52.0  85kgs      Huey   McDuck         -   m  00.06
17   6.0  52.0  85kgs      Huey   McDuck         -   m  06.12
29   6.0  52.0  85kgs      Huey   McDuck         -   m  12.18
41   6.0  52.0  85kgs      Huey   McDuck        68   f  00.06
53   6.0  52.0  85kgs      Huey   McDuck        75   f  06.12
65   6.0  52.0  85kgs      Huey   McDuck        72   f  12.18
6    7.0  19.0  56kgs     Dewey   McDuck         -   m  00.06
18   7.0  19.0  56kgs     Dewey   McDuck         -   m  06.12
30   7.0  19.0  56kgs     Dewey   McDuck         -   m  12.18
42   7.0  19.0  56kgs     Dewey   McDuck        71   f  00.06
54   7.0  19.0  56kgs     Dewey   McDuck        78   f  06.12
66   7.0  19.0  56kgs     Dewey   McDuck        75   f  12.18
7    8.0  32.0  78kgs      Scpy      Doo        78   m  00.06
19   8.0  32.0  78kgs      Scpy      Doo        76   m  06.12
31   8.0  32.0  78kgs      Scpy      Doo        75   m  12.18
43   8.0  32.0  78kgs      Scpy      Doo         -   f  00.06
55   8.0  32.0  78kgs      Scpy      Doo         -   f  06.12
67   8.0  32.0  78kgs      Scpy      Doo         -   f  12.18
8   10.0  12.0  45kgs     Louie   McDuck         -   m  00.06
20  10.0  12.0  45kgs     Louie   McDuck         -   m  06.12
32  10.0  12.0  45kgs     Louie   McDuck         -   m  12.18
44  10.0  12.0  45kgs     Louie   McDuck        92   f  00.06
56  10.0  12.0  45kgs     Louie   McDuck        95   f  06.12
68  10.0  12.0  45kgs     Louie   McDuck        87   f  12.18

In [ ]:
# Thay thế dấu gạch ngang bằng NaN để dễ dàng xử lý
patientheartrate['PulseRate'] = patientheartrate['PulseRate'].replace('-', np.nan)

# Tính số lượng và tỉ lệ phần trăm các giá trị bị thiếu
missing_count = patientheartrate['PulseRate'].isna().sum()
total_count = len(patientheartrate)
missing_percentage = (missing_count / total_count) * 100

print(f"Số lượng giá trị bị thiếu: {missing_count}")
print(f"Tỉ lệ phần trăm giá trị bị thiếu: {missing_percentage:.2f}%")

def fill_missing_pulse_rate(group):
    pulse_rate = group['PulseRate'].astype(float)

    # Phương pháp 1: Thay thế bằng giá trị trung bình liền trước và liền sau
    for i in range(len(pulse_rate)):
        if np.isnan(pulse_rate.iloc[i]):
            if i > 0 and i < len(pulse_rate) - 1 and not np.isnan(pulse_rate.iloc[i - 1]) and not np.isnan(pulse_rate.iloc[i + 1]):
                pulse_rate.iloc[i] = (pulse_rate.iloc[i - 1] + pulse_rate.iloc[i + 1]) / 2

    # Phương pháp 2: Thay thế bằng giá trị trung bình 2 giá liền trước
    for i in range(len(pulse_rate)):
        if np.isnan(pulse_rate.iloc[i]):
            if i > 1 and not np.isnan(pulse_rate.iloc[i - 1]) and not np.isnan(pulse_rate.iloc[i - 2]):
                pulse_rate.iloc[i] = (pulse_rate.iloc[i - 1] + pulse_rate.iloc[i - 2]) / 2

    # Phương pháp 3: Thay thế bằng giá trị trung bình 2 giá liền sau
    for i in range(len(pulse_rate)):
        if np.isnan(pulse_rate.iloc[i]):
            if i < len(pulse_rate) - 2 and not np.isnan(pulse_rate.iloc[i + 1]) and not np.isnan(pulse_rate.iloc[i + 2]):
                pulse_rate.iloc[i] = (pulse_rate.iloc[i + 1] + pulse_rate.iloc[i + 2]) / 2

    # Phương pháp 4: Trung bình của các giá trị huyết áp của người đó
    if pulse_rate.isna().sum() > 0:
        mean_individual = pulse_rate.mean()
        pulse_rate = pulse_rate.fillna(mean_individual)

    return pulse_rate

# Áp dụng hàm thay thế cho từng nhóm người
patientheartrate['PulseRate'] = patientheartrate.groupby('ID').apply(lambda group: fill_missing_pulse_rate(group)).reset_index(level=0, drop=True)

# Phương pháp 5: Trung bình của các giá trị huyết áp của nhóm giới tính
for sex in patientheartrate['sex'].unique():
    mean_sex = patientheartrate[patientheartrate['sex'] == sex]['PulseRate'].astype(float).mean()
    patientheartrate.loc[patientheartrate['sex'] == sex, 'PulseRate'] = patientheartrate.loc[patientheartrate['sex'] == sex, 'PulseRate'].fillna(mean_sex)

# Phương pháp 6: Trung bình của tất cả các giá trị huyết áp
mean_all = patientheartrate['PulseRate'].astype(float).mean()
patientheartrate['PulseRate'] = patientheartrate['PulseRate'].fillna(mean_all)

# Nếu vẫn còn giá trị thiếu, thay thế bằng mức ổn định trong y học (giả định là 70)
patientheartrate['PulseRate'] = patientheartrate['PulseRate'].fillna(70)

# In dữ liệu đã xử lý
print("Dữ liệu đã xử lý:")
print(patientheartrate.head())

Số lượng giá trị bị thiếu: 21
Tỉ lệ phần trăm giá trị bị thiếu: 51.22%
Dữ liệu đã xử lý:
     ID   Age Weight Firstname Lastname  PulseRate sex   Time
0   1.0  56.0  70kgs     Micky     Mous       72.0   m  00.06
12  1.0  56.0  70kgs     Micky     Mous       69.0   m  06.12
24  1.0  56.0  70kgs     Micky     Mous       71.0   m  12.18
36  1.0  56.0  70kgs     Micky     Mous       70.0   f  00.06
48  1.0  56.0  70kgs     Micky     Mous       70.5   f  06.12

In [ ]:
# Rút gọn dữ liệu, giữ lại các cột quan trọng
columns_to_keep = ['ID', 'Age', 'Weight', 'Firstname', 'Lastname', 'PulseRate', 'sex', 'Time']
patientheartrate_reduced = patientheartrate[columns_to_keep]

# Tái lập chỉ mục
patientheartrate_reduced = patientheartrate_reduced.reset_index(drop=True)

# Lưu dữ liệu đã xử lý thành tệp CSV mới với encoding 'utf-8'
patientheartrate_reduced.to_csv('patient_heart_rate_clean.csv', index=False, encoding='utf-8')

# In dữ liệu đã xử lý
print("Dữ liệu đã xử lý:")
print(patientheartrate_reduced.head())

Dữ liệu đã xử lý:
    ID   Age Weight Firstname Lastname  PulseRate sex   Time
0  1.0  56.0  70kgs     Micky     Mous       72.0   m  00.06
1  1.0  56.0  70kgs     Micky     Mous       69.0   m  06.12
2  1.0  56.0  70kgs     Micky     Mous       71.0   m  12.18
3  1.0  56.0  70kgs     Micky     Mous       70.0   f  00.06
4  1.0  56.0  70kgs     Micky     Mous       70.5   f  06.12